"""Validates and prepares model-generated (or user-edited) SQL before execution.

This is the safety-critical module: every query, whether freshly generated by
Claude or hand-edited by the user, must pass through validate_and_prepare_sql
before it is ever executed. See README "Safety" section for the full policy.

Both the user's question and the model's SQL output are treated as untrusted
input here — nothing about the generation step is trusted, only what this
module independently verifies via a real SQL AST (sqlglot), not regex
guessing.
"""

from dataclasses import dataclass

import sqlglot
from sqlglot import exp

# Statement types that must never appear anywhere in the parsed tree, not
# just at the root — catches anything smuggled into a subquery/CTE.
_DISALLOWED_EXPRESSION_TYPES = (
    exp.Insert,
    exp.Update,
    exp.Delete,
    exp.Drop,
    exp.Alter,
    exp.Create,
    exp.TruncateTable,
    exp.Merge,
    exp.Attach,
    exp.Detach,
    exp.Copy,
    exp.Pragma,
    exp.Command,  # catch-all for SET / CALL / INSTALL / LOAD / VACUUM / EXECUTE / etc.
    exp.Grant,
)

# Table-valued functions / extension mechanisms that could reach outside the
# whitelisted tables even inside an otherwise well-formed SELECT.
_DISALLOWED_FUNCTIONS = {
    "read_csv",
    "read_csv_auto",
    "read_parquet",
    "read_json",
    "read_json_auto",
    "read_text",
    "read_blob",
    "glob",
    "sniff_csv",
    "st_read",
    "postgres_scan",
    "sqlite_scan",
    "iceberg_scan",
    "delta_scan",
}


@dataclass(frozen=True)
class ValidationResult:
    is_valid: bool
    sql: str | None  # rewritten, safe-to-run SQL (LIMIT enforced), if valid
    error: str | None  # human-readable rejection reason, if invalid


def _func_name(func: exp.Func) -> str:
    # For unrecognized (DuckDB-specific) functions sqlglot parses them as
    # Anonymous, where .name holds the real name and .sql_name() does not.
    # For functions sqlglot does recognize, it's the reverse.
    if isinstance(func, exp.Anonymous):
        return (func.name or "").lower()
    return (func.sql_name() or "").lower()


def validate_and_prepare_sql(raw_sql: str, allowed_tables: list[str], max_rows: int) -> ValidationResult:
    if not raw_sql or not raw_sql.strip():
        return ValidationResult(False, None, "Empty query.")

    # Comments are rejected outright rather than stripped: correctly
    # stripping them per-dialect is itself a smuggling surface.
    if "--" in raw_sql or "/*" in raw_sql:
        return ValidationResult(False, None, "SQL comments are not allowed.")

    # Reject multi-statement input before parsing (sqlglot will happily
    # parse "SELECT ...; DROP TABLE ..." as two statements) — only one
    # optional trailing semicolon is tolerated.
    stripped = raw_sql.strip()
    body = stripped[:-1] if stripped.endswith(";") else stripped
    if ";" in body:
        return ValidationResult(False, None, "Only a single SQL statement is allowed.")

    if not body.strip():
        return ValidationResult(False, None, "Empty query.")

    try:
        statements = [s for s in sqlglot.parse(body, read="duckdb") if s is not None]
    except Exception as e:
        return ValidationResult(False, None, f"Could not parse SQL: {e}")

    if len(statements) != 1:
        return ValidationResult(False, None, "Only a single SQL statement is allowed.")

    tree = statements[0]

    if not isinstance(tree, (exp.Select, exp.Union)):
        return ValidationResult(False, None, "Only SELECT statements are allowed.")

    for node in tree.walk():
        if isinstance(node, _DISALLOWED_EXPRESSION_TYPES):
            return ValidationResult(False, None, f"Disallowed statement type: {node.key}")

    for func in tree.find_all(exp.Func):
        name = _func_name(func)
        if name in _DISALLOWED_FUNCTIONS:
            return ValidationResult(False, None, f"Function '{name}' is not allowed.")

    allowed_lower = {t.lower() for t in allowed_tables}
    for table in tree.find_all(exp.Table):
        table_name = table.name.lower()
        if table_name not in allowed_lower:
            label = table_name or "<table function>"
            return ValidationResult(False, None, f"Unknown or disallowed table '{label}'.")

    safe_tree = _enforce_row_limit(tree, max_rows)
    return ValidationResult(True, safe_tree.sql(dialect="duckdb"), None)


def _enforce_row_limit(tree: exp.Expression, max_rows: int) -> exp.Expression:
    if isinstance(tree, exp.Union):
        # Wrap unions in an outer SELECT so a single LIMIT governs the total
        # row count regardless of how the branches are limited individually.
        return exp.select("*").from_(exp.Subquery(this=tree, alias="wrapped")).limit(max_rows)

    limit_node = tree.args.get("limit")
    if limit_node is None:
        return tree.limit(max_rows)

    try:
        current_limit = int(limit_node.expression.this)
    except (TypeError, ValueError, AttributeError):
        current_limit = None

    if current_limit is None or current_limit > max_rows:
        tree.set("limit", exp.Limit(expression=exp.Literal.number(max_rows)))

    return tree
